stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests=true"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - apk add --no-cache maven docker-compose

build:
  stage: build
  script:
    # Build the Docker image for order-service
    - docker build -t $CI_REGISTRY_IMAGE/order-service:latest -f ./order-service/Dockerfile ./order-service
    # Build the Docker image for stock-service
    - docker build -t $CI_REGISTRY_IMAGE/stock-service:latest -f ./stock-service/Dockerfile ./stock-service
  artifacts:
    paths:
      - order-service/target/
      - stock-service/target/
  only:
    - main # Adjust to your default branch

test:
  stage: test
  script:
    # Pull the built Docker images
    - docker-compose up -d
    # Run integration tests
    - mvn -f order-service/pom.xml test
    - mvn -f stock-service/pom.xml test
  after_script:
    # Clean up services
    - docker-compose down -v

deploy:
  stage: deploy
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/order-service:latest
    - docker push $CI_REGISTRY_IMAGE/stock-service:latest
    - docker-compose -f docker-compose.prod.yml up -d
  only:
    - main 
